kind: Secret
apiVersion: v1
metadata:
  namespace: placeholdermanager-dev
  name: placeholdermanager-secret-0
  labels:
    app: placeholdermanager    
data:
  actuator.password: "{{actuator.password}}"
  git.password: "{{git.password}}"
type: Opaque
---
 